experiment1: Experiment1.class
	java -cp . Experiment1
	
experiment2: Experiment2.class
	java Experiment2
	
experiment3: Experiment3.class
	java Experiment3
	
Experiment1.class: Experiment1.java
	javac *.java
	
Experiment2.class: Experiment2.java
	javac *.java
	
Experiment3.class: Experiment3.java
	javac *.java
